### ISSUE TITLE
Use async StorageEngine

### ISSUE THREAD

**Issue by AzSiAz** [mergesort/Bodega#11]
Currently if you want to use `await` to read or write data in a `StorageEngine`, for exemple a `URLSession` or `CloudKit` based storage for a rest api, you can't do it since none of them are marked `async`, why not provide async variant or juste use async for everything ?

**Comment by AzSiAz** [comment]
Unfortunately as a primary JS developer I know too well the downside of function color...

But in this case a `StorageEngine` implementation is already an actor and external access already require the use of an `async` function, the change would be locked inside Bodega itself in this case no ?

**Comment by mergesort** [comment]
That's a really good point I hadn't considered. I quickly put [this change](https://github.com/mergesort/Bodega/commit/ebf532f36d6b53db6f5cef959a8e9acbb1b48578) together on [a branch](https://github.com/mergesort/Bodega/tree/2.0-async-storage-engine) and it seems to work.

1. I'm curious though, if it's already an actor shouldn't marking the functions as `async` when creating your own `StorageEngine` superfluous? Or is it because your intention is to use `URLSession` or `CloudKit` in your `StorageEngine`s `read` and `write` function when interacting with an external service.

2. Separately is it possible for you to create a Controller-like layer that handles all of the async functionality, rather than embedding it in a `StorageEngine`? I'm not opposed to treating a `StorageEngine` as a data or API controller given it's API resembles one, but I'm trying to think through whether that's a behavior I want to encourage rather than creating your own controller.

**Comment by AzSiAz** [comment]
1. In this case my intention was to be able to use an async local storage api if needed be, URLSession or CloudKit were just exemple but with the democratization of async/await in swift lot of things will probably go with asynchronous IO (such as a local filesystem implementation)

2. It's one of the possibility I am planning to explore, reimplementing something based on Bodega but with a local store and CloudKit sync persistence, but I don't think it should change the fact that a StorageEngine could be async compatible/only, GRDB.swift for exemple has an async API, despite being a local storage solution

**Comment by mergesort** [comment]
These are pretty compelling points, I'll close out this issue and merge that commit into 2.0. Thank you for the idea!

**Comment by AzSiAz** [comment]
Well more than anything thanks for listening 😊 and good luck with v2.0 of Boutique & Bodega
